--- 
$schema: "http://json-schema.org/draft-04/schema#"
additionalProperties: false
definitions: 
  ground_truth: 
    properties: 
      ground_truth: 
        properties: 
          type: 
            enum: 
              - "bioboxes.org:/profiling:0.9"
          value: {}
        required: 
          - type
          - value
    required: 
      - ground_truth
  prediction: 
    properties: 
      prediction: 
        properties: 
          type: 
            enum: 
              - "bioboxes.org:/profiling:0.9"
          value: {}
        required: 
          - type
          - value
    required: 
      - prediction
properties: 
  arguments: 
    additionalItems: false
    items: 
      oneOf: 
        - $ref: "#/definitions/prediction"
        - $ref: "#/definitions/ground_truth"
    minItems: 2
    required: 
      - prediction
      - ground_truth
    type: array
  version: 
    pattern: ^1.0.\d+$
    type: string
required: 
  - version
  - arguments
title: "Bioboxes Profiling Evaluation"
type: object

